services:
  # Masters Worker - Reference data (courses, bookmakers, jockeys, trainers, etc.)
  - type: web
    name: darkhorses-masters-worker
    env: python
    plan: starter  # Required for always-on scheduled tasks
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python3 render_worker.py
    envVars:
      - key: RACING_API_USERNAME
        sync: false
      - key: RACING_API_PASSWORD
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONDONTWRITEBYTECODE
        value: 1
